name: sensors_plus_platform_interface
publish_to: none
description: A common platform interface for the sensors_plus plugin.
version: 1.1.3
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  test: ^1.22.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"
